(ns aji.db)

(def default-db
  {:name "aji"
   :board-size 19
   :curr-turn "TURN_BLACK"
   :active-board {"1-A" {:stone nil  :liberties 2 :position "POSITION_CORNER_TOP_LEFT" :neighbors {:north nil :east "1-B" :south "2-A" :west nil}}
                  "1-B" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP" :neighbors {:north nil :east "1-A" :south "2-B" :west "1-C"}}
                  "1-C" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-D" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-E" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-F" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-G" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-H" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-I" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-J" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-K" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-L" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-M" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-N" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-O" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-P" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-Q" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-R" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-S" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                  "1-T" {:stone nil  :liberties 4 :position "POSITION_CORNER_TOP_RIGHT"}

                  "2-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT" :neighbors {:north "1-A" :east "2-B" :south "3-A" :west nil}}
                  "2-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "2-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "3-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "3-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "3-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "4-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "4-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "4-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "5-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "5-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "5-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "6-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "6-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "6-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "7-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "7-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "7-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "8-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "8-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "8-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "9-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "9-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "9-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "10-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "10-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "10-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "11-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "11-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "11-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "12-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "12-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "12-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "13-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "13-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "13-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "14-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "14-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "14-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "15-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "15-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "15-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "16-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "16-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "16-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "17-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "17-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "17-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "18-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                  "18-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                  "18-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                  "19-A" {:stone nil  :liberties 4 :position "POSITION_CORNER_BOTTOM_LEFT"}
                  "19-B" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-C" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-D" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-E" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-F" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-G" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-H" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-I" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-J" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-K" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-L" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-M" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-N" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-O" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-P" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-Q" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-R" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-S" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                  "19-T" {:stone nil  :liberties 4 :position "POSITION_CORNER_BOTTOM_RIGHT"}}
   :blank-board {"1-A" {:stone nil  :liberties 2 :position "POSITION_CORNER_TOP_LEFT" :neighbors {:north nil :east "1-B" :south "2-A" :west nil}}
                 "1-B" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-C" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-D" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-E" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-F" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-G" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-H" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-I" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-J" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-K" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-L" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-M" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-N" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-O" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-P" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-Q" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-R" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-S" {:stone nil  :liberties 4 :position "POSITION_SIDE_TOP"}
                 "1-T" {:stone nil  :liberties 4 :position "POSITION_CORNER_TOP_RIGHT"}

                 "2-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "2-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "2-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "3-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "3-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "3-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "4-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "4-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "4-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "5-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "5-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "5-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "6-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "6-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "6-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "7-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "7-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "7-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "8-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "8-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "8-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "9-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "9-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "9-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "10-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "10-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "10-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "11-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "11-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "11-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "12-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "12-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "12-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "13-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "13-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "13-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "14-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "14-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "14-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "15-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "15-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "15-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "16-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "16-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "16-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "17-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "17-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "17-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "18-A" {:stone nil  :liberties 4 :position "POSITION_SIDE_LEFT"}
                 "18-B" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-C" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-D" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-E" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-F" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-G" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-H" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-I" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-J" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-K" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-L" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-M" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-N" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-O" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-P" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-Q" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-R" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-S" {:stone nil  :liberties 4 :position "POSITION_MIDDLE"}
                 "18-T" {:stone nil  :liberties 4 :position "POSITION_SIDE_RIGHT"}

                 "19-A" {:stone nil  :liberties 4 :position "POSITION_CORNER_BOTTOM_LEFT"}
                 "19-B" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-C" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-D" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-E" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-F" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-G" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-H" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-I" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-J" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-K" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-L" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-M" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-N" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-O" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-P" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-Q" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-R" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-S" {:stone nil  :liberties 4 :position "POSITION_SIDE_BOTTOM"}
                 "19-T" {:stone nil  :liberties 4 :position "POSITION_CORNER_BOTTOM_RIGHT"}}})

